### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by ScreamZ** [SirwanAfifi/ts-faker#1]
Good job, that was exactly what I was looking for, even better if this was a Vscode plugin ahah.

Could you maybe add the capability to copy JSON directly without having to download a file? Thanks :)

And again, good job :)

**Comment by SirwanAfifi** [comment]
It's nice to hear you like it. It seems like a good idea to have a VS Code extension. Maybe I'll implement it in the future.

**PS:** The copy button will be implemented soon.

**Comment by SirwanAfifi** [comment]
Hi @ScreamZ, The copy feature is now available:
![image](https://user-images.githubusercontent.com/5256416/143326146-f3070082-3bdc-45f1-888d-be025123f468.png)

**Comment by ScreamZ** [comment]
Thank you 👍
