### ISSUE TITLE
Objects are not generated

### ISSUE THREAD

**Issue by bitttttten** [SirwanAfifi/ts-faker#3]
Hey! Lovely tool, although I noticed when trying to generate objects it gives me some kind of hash.

Input:

```ts
interface Banner {
  value: string;
  deepObject: {
    value: string
  }
};
```

Output:

```js
[{"name":"Banner","data":[{"value":"Voluptatem itaque molestiae ....","deepObject":"eAx5mOD4(e"}}]
```

![Screenshot 2022-11-17 at 10 21 34](https://user-images.githubusercontent.com/19930241/202406795-89018ab9-ddbd-4487-b65a-c395c663c87c.png)

**Comment by SirwanAfifi** [comment]
Hey @bitttttten glad you liked it,

Currently, the project does not support nested objects, but I will add it in the near future. In the meantime, if you have anything in mind, please send a pull request :)

**Comment by CarlosManotas** [comment]
@bitttttten I did something similar with nested interfaces and types, maybe can be [useful](https://carlosmanotas.com/lab/from-interfaces-to-json)
